- name: Instalando dependencias do modulo do k8s
  pip:
    name:
      - openshift
      - PyYAML

- name: Copiando o arquivo de deploy do app V1
  template:
    src: app-v1.yml.j2
    dest: /opt/giropops/app-v1.yml
    owner: root
    group: root
    mode: 0644
  register: copiando_deploy_app_v1

- name: Copiando o arquivo de deploy do app V2
  template:
    src: app-v2.yml.j2
    dest: /opt/giropops/app-v2.yml
    owner: root
    group: root
    mode: 0644
  register: copiando_deploy_app_v2

- name: Deploy do App V2
  k8s:
    state: present
    namespace: default
    src: /opt/giropops/app-v2.yml

- name: Scale down do App V1
  k8s:
    state: present
    namespace: default
    src: /opt/giropops/app-v1.yml

- name: Dentro de 02 minutos o app-v1 sera removido. Pressione Control+C para Cancelar
  pause:
    minutes: 2

- name: Removendo o APP V1
  k8s:
    state: absent
    namespace: default
    src: /opt/giropops/app-v1.yml



