- hosts: all
  become: yes
  user: root
  gather_facts: no
  pre_tasks:
  - name: 'Removendo Kubelet'
    raw: 'yum remove kubelet -y'    
  - name: 'Atualizando o repo'
    raw: 'yum update -y'
  roles:
  - { role: install-k8s, tags: ["install_k8s_role"] }
   
- hosts: k8s_master
  become: yes
  user: root
  roles:
  - { role: create-cluster, tags: ["create_cluster_role"] }

- hosts: k8s_workers
  become: yes
  user: root
  roles:
  - { role: join-workers, tags: ["join_workers_roles"] }

- hosts: k8s_master
  become: yes
  user: root
  roles:
  - { role: install-helm, tags: ["install_helm3_role"] }


- hosts: k8s_master
  become: yes
  user: root
  roles:
  - { role: install-monit-tools, tags: ["install_monit_tools_role"] }
