- name: Adicionando o Repo no Helm
  shell: helm repo add stable {{ url_repo_helm }}
  register: add_repo_helm
  changed_when: '"been added to" in add_repo_helm.stdout'


- name: helm update
  shell: helm repo update
  register: prometheus_repo_update
  changed_when: '"Update Complete" in prometheus_repo_update.stdout'

- name: Instalando o Prometheus Operator
  shell: helm install {{ deploy_prometheus }}
  register: install_prometheus


